name = "GeoStatsDevTools"
uuid = "19e549d1-356f-5655-9f3d-c1d6136da705"
author = "Júlio Hoffimann <julio.hoffimann@gmail.com>"
version = "0.4.5"

[deps]
GeoStatsBase = "323cb8eb-fbf6-51c0-afd0-f8fba70507b2"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
GeoStatsBase = "≥ 0.4.3"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
